### ISSUE TITLE
Front end architecture 

### ISSUE THREAD

**Issue by des-des** [jgne/bubbles#1]
How do we want to structure our page on the front end?

Options:
  1. Have a single HTML document with each separate page being a div. Using css to transition between pages
  2. Use ajax requests to get content for subsequent pages. Returned data then rendered with js on front. 
  3. Use more than one HTML document. Normal page requests/links moving between two pages (ie not a one page app)
  4. Use REACT with react router.

**Comment by des-des** [comment]
Things to consider:
  1. page load
  2. transition feel / speed ect
  3. Organisation of code. ie how much complexity will we introduce to our code?
  4. How much time will we need to spend learning new technology?
  5. Will this approach hold us back in future sprints?

**Comment by des-des** [comment]
#### One page app with css transitions

one page app on [wikipedia](https://en.wikipedia.org/wiki/Single-page_application). Super useful background! 

##### pros
  * native app feel! no page loads
  * can be used in conjunction option 2 (loading pages with in ajax requests) ***if*** our page get too heavy

##### cons:
  * To do this well we either have to use a framework or do lots of setup work. React, ember, angular and meteor would all help with this

If we are not using a framework I think [this](http://tutorialzine.com/2015/02/single-page-app-without-a-framework/) would be a great place to start!

**Comment by naazy** [comment]
# Use React with react router

### PROS
- Really fast rendering for different components
- Can add screens and UI easily
- Nesting is dealt with simply
- Manages back buttons and history locations
- Gives links and routes active classes so you don’t have to

### CONS
- a much longer set up time, increased complexity, and more difficult deployment
- users have to download the whole bundle before your app is usable
 
### TUTORIALS
- FAC6 readme: https://github.com/FAC6/book/blob/master/patterns/week9/reactRouter.md
- to set up a single page react web app with react router (and webpack): http://jmfurlott.com/tutorial-setting-up-a-single-page-react-web-app-with-react-router-and-webpack/
- using react router to match arbitrary urls in your app: http://gregtrowbridge.com/using-react-router-to-match-arbitrary-urls-in-your-app/

**Comment by jackcarlisle** [comment]
We have decided to use REACT for our single page app.

**Comment by thegsi** [comment]
## Replacing html on page with XMLHTTP

### Pros
We are familiar with method
High speed possible but not as quick as React
Transitions can work well but may be  steep learning curve,

### Cons
Could be less organised code
Shallow learning curve as we are all familiar
Could work on in future again but more difficult to pick up than with framework

Must be used in conjunction with div containers on html page to begin with.

### Links
http://danielnouri.org/notes/2011/03/13/an-ajax-page-update-mini-tutorial/
http://code.tutsplus.com/tutorials/important-considerations-when-building-single-page-web-apps--net-29356
