### ISSUE TITLE
Restaurant Page

### ISSUE THREAD

**Issue by katpas** [jgne/bubbles#199]
- [x] Logos not images
- [x] 6 per page 
- [x] Varies depending on north or south terminal
- [ ] Sign posting "you can order from multiple restaurants, please pick your first restaurant here" (don't show if they're on this screen from choosing order from elsewhere). (check with Jonny)
- [x] Give Jonny JSON format

**Comment by katpas** [comment]
South Terminal

Grain Store

Wagamama

Pret à Manger

Wonder Tree

Nando’s

Caviar House

 

North Terminal

Pret à Manger

YO! Sushi

Wagamama

Comptoir Libanais

Caviar House

Jamie’s

**Comment by rug1** [comment]
Needs South Terminal data still

**Comment by katpas** [comment]
- [ ] Find Images for missing restaurants
- [ ] Add button styling to order by restaurant
