### ISSUE TITLE
Restaurant Menu Page

### ISSUE THREAD

**Issue by katpas** [jgne/bubbles#200]
- Change Colours, remove image?

**Comment by katpas** [comment]
Vertically align text over image

**Comment by katpas** [comment]
Waiting for Jonny to send altered text.

**Comment by katpas** [comment]
Restaurant Description

**Comment by katpas** [comment]
Font-colour on Restaurant Menu Page

**Comment by rug1** [comment]
![sandwiches_desktop](https://cloud.githubusercontent.com/assets/13667174/16146338/6edb138e-3475-11e6-962a-504e73dccc4d.jpg)

**Comment by rug1** [comment]
![wondertree-opens-at-heathrow-terminal-22](https://cloud.githubusercontent.com/assets/13667174/16146343/73571106-3475-11e6-8d9f-6650dcb6b27d.jpg)
