### ISSUE TITLE
Build setup

### ISSUE THREAD

**Issue by des-des** [jgne/bubbles#23]
To do:
 - [x] research how hapi + webpack + react can work together.
 - [x] get a test environment set up
 - [x] set up our build process and get this working with a basic server
 - [x] set up continuous deployment
 - [x] set up travis
 - [x] think about pre-commit hooks. (ie should we do linting + minimum coverage etc as pre-commit hooks)
 - [x] set up react router

**Comment by jackcarlisle** [comment]
* React router

**Comment by naazy** [comment]
- have set up continuous deployment to heroku: https://bubbles-mvp.herokuapp.com/

**Comment by naazy** [comment]
- have set up travis

**Comment by des-des** [comment]
I think will be fine without using inheritance.

**Comment by jackcarlisle** [comment]
build setup complete
