### ISSUE TITLE
Non-basket components/templates

### ISSUE THREAD

**Issue by jackcarlisle** [jgne/bubbles#25]
- [x] Select airport page
 - [x] Airport not served landing page
 - [x] Fight details
 - [x] About page
 - [x] Dummy login page
 - [x] Create account (personal details + payment)
 - [x] Payment page
 - [x] Order confirmation

**Comment by naazy** [comment]
- intro/flight
- payment/confirmation

**Comment by jackcarlisle** [comment]
Initial templating done, styling to come
