### ISSUE TITLE
React router research

### ISSUE THREAD

**Issue by des-des** [jgne/bubbles#28]
Should we use the react-router component? Why and how?

**Comment by jackcarlisle** [comment]
https://github.com/FAC6/book/blob/master/patterns/week9/reactRouter.md

**Comment by des-des** [comment]
[github repository](https://github.com/rackt/react-router). [here](http://codepen.io/luisrudge/pen/QbEeOR) is a minimal running example of css transitions with react router and [here](https://github.com/rackt/react-router/issues/17) is a github issue talking about transitions with react router.

**Comment by des-des** [comment]
Pros
  * easy linking from page to page
  * gives our pages urls

Cons
   * extra, unneeded complexity?

#### Question

Is the benefit brought by having this easy way to move between different views worth the extra complexity?

**Comment by des-des** [comment]
this issue a part of #23

**Comment by des-des** [comment]
OK going with react router. Seems easy to use.
