### ISSUE TITLE
Hapi with React

### ISSUE THREAD

**Issue by thegsi** [jgne/bubbles#31]
https://medium.com/@tribou/serving-react-and-flux-with-hapi-and-webpack-213afacf94ea#.lj3g1inhn

https://github.com/jedireza/hapi-react-views

https://github.com/tanepiper/quorra

https://github.com/tribou/react-todo/tree/1.5.1

**Comment by des-des** [comment]
The main example in the [hapi-react-views repo](https://github.com/jedireza/hapi-react-views) seems to be rendering server-side. Do we need to render client side ([isomorphically](https://github.com/jedireza/hapi-react-views#remounting-on-the-client-universalisomorphic)) also? Some sample code of how to do this [here](https://github.com/jedireza/hapi-react-views/tree/master/examples/remount). @jackcarlisle how would this feed into react router?

**Comment by des-des** [comment]
OK as discussion we will make *very* basic hapi server. We will bundle up our app using webpack and do all rendering client side

**Comment by des-des** [comment]
@thegsi close this now?
