### ISSUE TITLE
Research: Simple web form pages with react components

### ISSUE THREAD

**Issue by jackcarlisle** [jgne/bubbles#43]
Research into how we can create form components using React - how to implement and connect these components

**Comment by jackcarlisle** [comment]
Running into issues with React router - possible that it's due to the React modules and not our code

**Comment by jackcarlisle** [comment]
Problem solved: Our components were nested within the index whereas they should have been flat

**Comment by des-des** [comment]
great bunch of react form components on npm example [here](http://twisty.github.io/formsy-react-components/playground/)! Thinking react was good choice..

**Comment by jackcarlisle** [comment]
Decided to go with library from [this repo](https://github.com/twisty/formsy-react-components) as mentioned above.
